# Actual tasks will be run here

# ---
# - name: KMIP KMS | Fetch kmip certs to local ansible server
#   become: yes
#   fetch:
#     src: "/etc/pykmip/{{item}}"
#     dest: "/tmp/pykmip/{{item}}"
#     flat: yes
#   with_items:
#     - client_certificate.pem
#     - root_certificate.pem
#     - client_key.pem

---
- name: Install Pre-Req | Install the basic dependencies 
  apt:
    name: 
      - build-essential
      - autoconf
      - bison 
      - gawk 
      - ninja-build
      - python3
      - python3-click
      - python3-jinja2
      - wget
    state: present
    when: ansible_distribution == "Ubuntu"

- name: Install Pre-Req | GDB support related dependencies
  apt:
    name: 
      - libunwind8
      - python3-pyelftools
      - python3-pytest
    state: present
    when: ansible_distribution == "Ubuntu"

- name: Install Pre-Req | GCC dependencies
  apt:
    name: 
      - libgmp-dev
      - libmpfr-dev
      - libmpc-dev
      - libisl-dev
    state: present
    when: ansible_distribution == "Ubuntu"

- name: Install Pre-Req | SGX related dependencies 
  apt:
    name: 
      - libcurl4-openssl-dev
      - libprotobuf-c-dev
      - protobuf-c-compiler
      - python3-pip
      - python3-protobuf
    state: present
    when: ansible_distribution == "Ubuntu"